version: '3'

services:
  nuxt:
    container_name: ${dir}
    build: .
    tty: true
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./${dir}:/app
      - /app/node_modules
    ports:
      - "3000:3000"
